import type { Gacha, Prize, PointPackage, PointTransaction, Profile } from '@/types/database'

// --- Gacha definitions ---

const GACHA_IDS = {
  iphone: 'demo-gacha-iphone-17-pro',
  ps5: 'demo-gacha-ps5-special',
  beginner: 'demo-gacha-beginners',
} as const

export const demoGachas: Gacha[] = [
  {
    id: GACHA_IDS.iphone,
    name: 'iPhone 17 Pro ガチャ',
    description: '最新iPhone 17 Proが当たるチャンス！S賞は256GBモデル、ラストワン賞はPro Max 1TB！',
    price: 10000,
    type: 'normal',
    image_url: 'https://value-gacha.com/wp-content/uploads/2025/03/IMG_6656.jpg',
    is_active: true,
    total_count: 100,
    remaining_count: 42,
    daily_limit: null,
    pity_count: 50,
    pity_rank: 'A',
    min_total_spent: null,
    sale_start_at: null,
    sale_end_at: null,
    sort_order: 1,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: GACHA_IDS.ps5,
    name: 'PS5 スペシャルガチャ',
    description: 'PS5本体やコントローラーが当たる！ラストワン賞はPS5+ソフト5本セット！',
    price: 5000,
    type: 'normal',
    image_url: 'https://value-gacha.com/wp-content/uploads/2025/03/IMG_6688.jpg',
    is_active: true,
    total_count: 50,
    remaining_count: 28,
    daily_limit: null,
    pity_count: 30,
    pity_rank: 'A',
    min_total_spent: null,
    sale_start_at: null,
    sale_end_at: null,
    sort_order: 2,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: GACHA_IDS.beginner,
    name: 'ビギナーズガチャ',
    description: '初心者向け！毎日3回まで挑戦可能。Nintendo Switchが当たるかも！',
    price: 3000,
    type: 'daily',
    image_url: 'https://value-gacha.com/wp-content/uploads/2025/03/IMG_6500.jpg',
    is_active: true,
    total_count: null,
    remaining_count: null,
    daily_limit: 3,
    pity_count: null,
    pity_rank: null,
    min_total_spent: null,
    sale_start_at: null,
    sale_end_at: null,
    sort_order: 3,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
]

// --- Prize definitions ---

const iphonePrizes: Prize[] = [
  {
    id: 'demo-prize-iphone-s',
    gacha_id: GACHA_IDS.iphone,
    name: 'iPhone 17 Pro 256GB',
    description: '最新のiPhone 17 Pro 256GBモデル',
    rank: 'S',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/06/50000P-1.png',
    probability: 2,
    stock: 1,
    initial_stock: 1,
    is_last_one: false,
    once_per_user: true,
    exchange_points: 50000,
    sort_order: 1,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-iphone-a',
    gacha_id: GACHA_IDS.iphone,
    name: 'AirPods Pro',
    description: '第3世代 AirPods Pro',
    rank: 'A',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/06/10000P.png',
    probability: 8,
    stock: 3,
    initial_stock: 5,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 15000,
    sort_order: 2,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-iphone-b',
    gacha_id: GACHA_IDS.iphone,
    name: 'Apple Watch SE',
    description: 'Apple Watch SE 第2世代',
    rank: 'B',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/5000P-1.png',
    probability: 20,
    stock: 10,
    initial_stock: 15,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 5000,
    sort_order: 3,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-iphone-c',
    gacha_id: GACHA_IDS.iphone,
    name: 'Lightningケーブルセット',
    description: 'Apple純正ケーブル3本セット',
    rank: 'C',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/500P-1.png',
    probability: 70,
    stock: 86,
    initial_stock: 100,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 500,
    sort_order: 4,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-iphone-last',
    gacha_id: GACHA_IDS.iphone,
    name: 'iPhone 17 Pro Max 1TB',
    description: '最上位モデル iPhone 17 Pro Max 1TB',
    rank: 'last_one',
    image_url: 'https://value-gacha.com/wp-content/uploads/2025/03/IMG_6656.jpg',
    probability: 0,
    stock: 1,
    initial_stock: 1,
    is_last_one: true,
    once_per_user: true,
    exchange_points: null,
    sort_order: 5,
    created_at: '2026-03-01T00:00:00Z',
  },
]

const ps5Prizes: Prize[] = [
  {
    id: 'demo-prize-ps5-s',
    gacha_id: GACHA_IDS.ps5,
    name: 'PS5 本体',
    description: 'PlayStation 5 デジタル・エディション',
    rank: 'S',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/50000.png',
    probability: 3,
    stock: 1,
    initial_stock: 1,
    is_last_one: false,
    once_per_user: true,
    exchange_points: 30000,
    sort_order: 1,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-ps5-a',
    gacha_id: GACHA_IDS.ps5,
    name: 'DualSense コントローラー 2個セット',
    description: 'PS5用ワイヤレスコントローラー2個',
    rank: 'A',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/10000.png',
    probability: 10,
    stock: 5,
    initial_stock: 5,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 8000,
    sort_order: 2,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-ps5-b',
    gacha_id: GACHA_IDS.ps5,
    name: 'PSNカード \u00a510,000',
    description: 'PlayStation Network ストアカード',
    rank: 'B',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/5000.png',
    probability: 25,
    stock: 15,
    initial_stock: 20,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 3000,
    sort_order: 3,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-ps5-c',
    gacha_id: GACHA_IDS.ps5,
    name: 'PSNカード \u00a51,000',
    description: 'PlayStation Network ストアカード',
    rank: 'C',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/5000.png',
    probability: 62,
    stock: 29,
    initial_stock: 50,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 300,
    sort_order: 4,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-ps5-last',
    gacha_id: GACHA_IDS.ps5,
    name: 'PS5 + ソフト5本セット',
    description: 'PS5本体と人気ソフト5本のスペシャルセット',
    rank: 'last_one',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/50000.png',
    probability: 0,
    stock: 1,
    initial_stock: 1,
    is_last_one: true,
    once_per_user: true,
    exchange_points: null,
    sort_order: 5,
    created_at: '2026-03-01T00:00:00Z',
  },
]

const beginnerPrizes: Prize[] = [
  {
    id: 'demo-prize-beginner-s',
    gacha_id: GACHA_IDS.beginner,
    name: 'Nintendo Switch',
    description: 'Nintendo Switch 本体（有機ELモデル）',
    rank: 'S',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/100000.png',
    probability: 5,
    stock: 2,
    initial_stock: 3,
    is_last_one: false,
    once_per_user: true,
    exchange_points: 20000,
    sort_order: 1,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-beginner-a',
    gacha_id: GACHA_IDS.beginner,
    name: 'ワイヤレスイヤホン',
    description: 'ノイズキャンセリング搭載ワイヤレスイヤホン',
    rank: 'A',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/1000.png',
    probability: 15,
    stock: 8,
    initial_stock: 10,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 5000,
    sort_order: 2,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-beginner-b',
    gacha_id: GACHA_IDS.beginner,
    name: 'Amazonギフト券 \u00a53,000',
    description: 'Amazonギフト券 3,000円分',
    rank: 'B',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/500.png',
    probability: 30,
    stock: 20,
    initial_stock: 30,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 1500,
    sort_order: 3,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-beginner-c',
    gacha_id: GACHA_IDS.beginner,
    name: 'Amazonギフト券 \u00a5500',
    description: 'Amazonギフト券 500円分',
    rank: 'C',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/500.png',
    probability: 50,
    stock: 50,
    initial_stock: 80,
    is_last_one: false,
    once_per_user: false,
    exchange_points: 200,
    sort_order: 4,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'demo-prize-beginner-last',
    gacha_id: GACHA_IDS.beginner,
    name: 'Nintendo Switch + ソフト3本',
    description: 'Nintendo Switch本体と人気ソフト3本のセット',
    rank: 'last_one',
    image_url: 'https://value-gacha.com/wp-content/uploads/2024/05/100000.png',
    probability: 0,
    stock: 1,
    initial_stock: 1,
    is_last_one: true,
    once_per_user: true,
    exchange_points: null,
    sort_order: 5,
    created_at: '2026-03-01T00:00:00Z',
  },
]

export const demoPrizes: Record<string, Prize[]> = {
  [GACHA_IDS.iphone]: iphonePrizes,
  [GACHA_IDS.ps5]: ps5Prizes,
  [GACHA_IDS.beginner]: beginnerPrizes,
}

export const allDemoPrizes: Prize[] = [
  ...iphonePrizes,
  ...ps5Prizes,
  ...beginnerPrizes,
]

// --- Point packages (same 8 from schema.sql) ---

export const demoPointPackages: PointPackage[] = [
  { id: 'demo-pkg-1', name: '500 PT', points: 500, price: 500, is_active: true, sort_order: 1, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-2', name: '1,000 PT', points: 1000, price: 1000, is_active: true, sort_order: 2, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-3', name: '5,000 PT', points: 5000, price: 5000, is_active: true, sort_order: 3, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-4', name: '10,000 PT', points: 10000, price: 10000, is_active: true, sort_order: 4, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-5', name: '50,000 PT', points: 50000, price: 50000, is_active: true, sort_order: 5, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-6', name: '100,000 PT', points: 100000, price: 100000, is_active: true, sort_order: 6, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-7', name: '200,000 PT', points: 200000, price: 200000, is_active: true, sort_order: 7, created_at: '2026-03-01T00:00:00Z' },
  { id: 'demo-pkg-8', name: '500,000 PT', points: 500000, price: 500000, is_active: true, sort_order: 8, created_at: '2026-03-01T00:00:00Z' },
]

// --- Demo profile ---

export const demoProfile: Profile = {
  id: 'demo-user-001',
  email: 'demo@example.com',
  display_name: 'デモユーザー',
  phone: null,
  postal_code: null,
  prefecture: null,
  city: null,
  address: null,
  building: null,
  point_balance: 10000,
  role: 'admin',
  created_at: '2026-03-01T00:00:00Z',
  updated_at: '2026-03-28T00:00:00Z',
}

// --- Demo gacha results (won prizes) ---

export const demoGachaResults: { id: string; user_id: string; gacha_id: string; prize_id: string; points_spent: number; status: string; created_at: string; prize: Prize; gacha: { name: string } }[] = [
  {
    id: 'demo-result-1',
    user_id: demoProfile.id,
    gacha_id: GACHA_IDS.iphone,
    prize_id: 'demo-prize-iphone-b',
    points_spent: 10000,
    status: 'won',
    created_at: '2026-03-27T14:30:00Z',
    prize: iphonePrizes[2],
    gacha: { name: 'iPhone 17 Pro ガチャ' },
  },
  {
    id: 'demo-result-2',
    user_id: demoProfile.id,
    gacha_id: GACHA_IDS.ps5,
    prize_id: 'demo-prize-ps5-c',
    points_spent: 5000,
    status: 'shipped',
    created_at: '2026-03-26T10:15:00Z',
    prize: ps5Prizes[3],
    gacha: { name: 'PS5 スペシャルガチャ' },
  },
  {
    id: 'demo-result-3',
    user_id: demoProfile.id,
    gacha_id: GACHA_IDS.beginner,
    prize_id: 'demo-prize-beginner-a',
    points_spent: 3000,
    status: 'won',
    created_at: '2026-03-25T18:00:00Z',
    prize: beginnerPrizes[1],
    gacha: { name: 'ビギナーズガチャ' },
  },
]

// --- Demo point transactions ---

export const demoTransactions: PointTransaction[] = [
  {
    id: 'demo-tx-1',
    user_id: demoProfile.id,
    amount: 10000,
    type: 'purchase',
    description: 'ポイント購入 10,000 PT',
    stripe_payment_intent_id: null,
    created_at: '2026-03-25T09:00:00Z',
  },
  {
    id: 'demo-tx-2',
    user_id: demoProfile.id,
    amount: -3000,
    type: 'gacha',
    description: 'ビギナーズガチャ 1回',
    stripe_payment_intent_id: null,
    created_at: '2026-03-25T18:00:00Z',
  },
  {
    id: 'demo-tx-3',
    user_id: demoProfile.id,
    amount: 10000,
    type: 'purchase',
    description: 'ポイント購入 10,000 PT',
    stripe_payment_intent_id: null,
    created_at: '2026-03-26T08:00:00Z',
  },
  {
    id: 'demo-tx-4',
    user_id: demoProfile.id,
    amount: -5000,
    type: 'gacha',
    description: 'PS5 スペシャルガチャ 1回',
    stripe_payment_intent_id: null,
    created_at: '2026-03-26T10:15:00Z',
  },
  {
    id: 'demo-tx-5',
    user_id: demoProfile.id,
    amount: -10000,
    type: 'gacha',
    description: 'iPhone 17 Pro ガチャ 1回',
    stripe_payment_intent_id: null,
    created_at: '2026-03-27T14:30:00Z',
  },
]

// --- Helper: pick a random prize based on probability ---

export function pickRandomDemoPrize(gachaId: string): Prize | null {
  const prizes = demoPrizes[gachaId]
  if (!prizes) return null

  // Filter out last_one prizes (probability 0)
  const playable = prizes.filter(p => p.probability > 0 && p.stock > 0)
  if (playable.length === 0) return null

  const totalProb = playable.reduce((sum, p) => sum + p.probability, 0)
  let rand = Math.random() * totalProb
  for (const prize of playable) {
    rand -= prize.probability
    if (rand <= 0) return prize
  }
  return playable[playable.length - 1]
}
